import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import "./floating-input-select.scss";
const FloatingSelect = ({ label, options, value = "", onChange, error, placeholder = "Chọn...", required = false, }) => {
    const [isFocused, setIsFocused] = useState(false);
    const hasValue = value !== "";
    return (_jsxs("div", { className: "floating-select", children: [_jsxs("div", { className: `floating-select__wrapper ${error ? "floating-select__wrapper--error" : ""}`, children: [_jsxs("select", { value: value, onChange: onChange, onFocus: () => setIsFocused(true), onBlur: () => setIsFocused(false), className: `floating-select__input ${hasValue || isFocused ? "floating-select__input--filled" : ""}`, children: [_jsx("option", { value: "", disabled: true, hidden: true, children: placeholder }), options.map((option) => (_jsx("option", { value: option.value, children: option.label }, option.value)))] }), _jsxs("label", { className: `floating-select__label ${hasValue || isFocused ? "floating-select__label--float" : ""}`, children: [label, required && _jsx("span", { className: "floating-select__required", children: "*" })] }), _jsx("div", { className: "floating-select__arrow", children: _jsx("svg", { width: "20", height: "20", viewBox: "0 0 24 24", children: _jsx("polyline", { points: "6 9 12 15 18 9", fill: "none", stroke: "currentColor", strokeWidth: "2" }) }) }), error && (_jsx("div", { className: "floating-select__error-icon", children: _jsxs("svg", { width: "20", height: "20", viewBox: "0 0 24 24", children: [_jsx("circle", { cx: "12", cy: "12", r: "10", fill: "none", stroke: "currentColor", strokeWidth: "2" }), _jsx("line", { x1: "12", y1: "8", x2: "12", y2: "12", stroke: "currentColor", strokeWidth: "2" }), _jsx("line", { x1: "12", y1: "16", x2: "12.01", y2: "16", stroke: "currentColor", strokeWidth: "2" })] }) }))] }), error && _jsx("p", { className: "floating-select__error-message", children: error })] }));
};
export default FloatingSelect;
